// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/fullmoonbk.tga
gfx/env/fullmoondn.tga
gfx/env/fullmoonft.tga
gfx/env/fullmoonlf.tga
gfx/env/fullmoonrt.tga
gfx/env/fullmoonup.tga
models/player/alien/alien.bmp
models/player/alien/alien.mdl
models/player/banshee/banshee.bmp
models/player/banshee/banshee.mdl
models/player/demon/demon.bmp
models/player/demon/demon.mdl
models/player/reaper/reaper.bmp
models/player/reaper/reaper.mdl
models/player/scarecrow/scarecrow.bmp
models/player/scarecrow/scarecrow.mdl
models/player/scream/scream.bmp
models/player/scream/scream.mdl
models/player/vamp/vamp.bmp
models/player/vamp/vamp.mdl
models/player/werewolf/werewolf.bmp
models/player/werewolf/werewolf.mdl
models/player/witch/witch.bmp
models/player/witch/witch.mdl
models/schall/agrunt.mdl
models/schall/big_mom.mdl
models/schall/controller.mdl
models/schall/garg.mdl
models/schall/hassassin.mdl
models/schall/headcrab.mdl
models/schall/hgrunt.mdl
models/schall/hgrunt_devil.mdl
models/schall/hornet.mdl
models/schall/houndeye.mdl
models/schall/icky_stalker.mdl
models/schall/islave.mdl
models/schall/p_9mmar.mdl
models/schall/p_crowbar.mdl
models/schall/p_squeak.mdl
models/schall/scientist.mdl
models/schall/v_9mmar.mdl
models/schall/v_crowbar.mdl
models/schall/v_squeak.mdl
models/schall/w_9mmar.mdl
models/schall/w_battery.mdl
models/schall/w_crowbar.mdl
models/schall/w_medkit.mdl
models/schall/w_squeak.mdl
models/schall/zombie.mdl
schall.wad
sound/schall/ambience/crumble.wav
sound/schall/ambience/kids.wav
sound/schall/ambience/mob.wav
sound/schall/aslave/slv_alert1.wav
sound/schall/aslave/slv_alert3.wav
sound/schall/aslave/slv_alert4.wav
sound/schall/aslave/slv_die1.wav
sound/schall/aslave/slv_die2.wav
sound/schall/aslave/slv_pain1.wav
sound/schall/aslave/slv_pain2.wav
sound/schall/aslave/slv_word1.wav
sound/schall/aslave/slv_word2.wav
sound/schall/aslave/slv_word3.wav
sound/schall/aslave/slv_word4.wav
sound/schall/aslave/slv_word5.wav
sound/schall/aslave/slv_word6.wav
sound/schall/aslave/slv_word7.wav
sound/schall/aslave/slv_word8.wav
sound/schall/controller/con_alert1.wav
sound/schall/controller/con_alert2.wav
sound/schall/controller/con_alert3.wav
sound/schall/controller/con_attack1.wav
sound/schall/controller/con_attack2.wav
sound/schall/controller/con_attack3.wav
sound/schall/controller/con_die1.wav
sound/schall/controller/con_die2.wav
sound/schall/controller/con_idle1.wav
sound/schall/controller/con_idle2.wav
sound/schall/controller/con_idle3.wav
sound/schall/controller/con_idle4.wav
sound/schall/controller/con_idle5.wav
sound/schall/controller/con_pain1.wav
sound/schall/controller/con_pain2.wav
sound/schall/controller/con_pain3.wav
sound/schall/garg/gar_alert1.wav
sound/schall/garg/gar_alert2.wav
sound/schall/garg/gar_alert3.wav
sound/schall/garg/gar_attack1.wav
sound/schall/garg/gar_attack2.wav
sound/schall/garg/gar_attack3.wav
sound/schall/garg/gar_breathe1.wav
sound/schall/garg/gar_breathe2.wav
sound/schall/garg/gar_breathe3.wav
sound/schall/garg/gar_die1.wav
sound/schall/garg/gar_die2.wav
sound/schall/garg/gar_idle1.wav
sound/schall/garg/gar_idle2.wav
sound/schall/garg/gar_idle3.wav
sound/schall/garg/gar_idle4.wav
sound/schall/garg/gar_pain1.wav
sound/schall/garg/gar_pain2.wav
sound/schall/garg/gar_pain3.wav
sound/schall/garg/gar_step1.wav
sound/schall/garg/gar_step2.wav
sound/schall/headcrab/hc_alert1.wav
sound/schall/headcrab/hc_alert2.wav
sound/schall/headcrab/hc_attack1.wav
sound/schall/headcrab/hc_attack2.wav
sound/schall/headcrab/hc_attack3.wav
sound/schall/headcrab/hc_die1.wav
sound/schall/headcrab/hc_die2.wav
sound/schall/headcrab/hc_headbite.wav
sound/schall/headcrab/hc_idle1.wav
sound/schall/headcrab/hc_idle2.wav
sound/schall/headcrab/hc_idle3.wav
sound/schall/headcrab/hc_idle4.wav
sound/schall/headcrab/hc_idle5.wav
sound/schall/headcrab/hc_pain1.wav
sound/schall/headcrab/hc_pain2.wav
sound/schall/headcrab/hc_pain3.wav
sound/schall/hornet/ag_buzz1.wav
sound/schall/hornet/ag_buzz2.wav
sound/schall/hornet/ag_buzz3.wav
sound/schall/hornet/ag_fire1.wav
sound/schall/hornet/ag_fire3.wav
sound/schall/hornet/ag_hornethit1.wav
sound/schall/hornet/ag_hornethit2.wav
sound/schall/hornet/ag_hornethit3.wav
sound/schall/houndeye/he_alert1.wav
sound/schall/houndeye/he_alert2.wav
sound/schall/houndeye/he_alert3.wav
sound/schall/houndeye/he_attack1.wav
sound/schall/houndeye/he_attack2.wav
sound/schall/houndeye/he_attack3.wav
sound/schall/houndeye/he_blast1.wav
sound/schall/houndeye/he_blast2.wav
sound/schall/houndeye/he_blast3.wav
sound/schall/houndeye/he_die1.wav
sound/schall/houndeye/he_die2.wav
sound/schall/houndeye/he_die3.wav
sound/schall/houndeye/he_hunt1.wav
sound/schall/houndeye/he_hunt2.wav
sound/schall/houndeye/he_hunt3.wav
sound/schall/houndeye/he_hunt4.wav
sound/schall/houndeye/he_idle1.wav
sound/schall/houndeye/he_idle2.wav
sound/schall/houndeye/he_idle3.wav
sound/schall/houndeye/he_idle4.wav
sound/schall/houndeye/he_pain1.wav
sound/schall/houndeye/he_pain2.wav
sound/schall/houndeye/he_pain3.wav
sound/schall/houndeye/he_pain4.wav
sound/schall/houndeye/he_pain5.wav
sound/schall/squeek/sqk_blast1.wav
sound/schall/squeek/sqk_deploy1.wav
sound/schall/squeek/sqk_die1.wav
sound/schall/squeek/sqk_hunt1.wav
sound/schall/squeek/sqk_hunt2.wav
sound/schall/squeek/sqk_hunt3.wav
sound/schall/zombie/zo_alert10.wav
sound/schall/zombie/zo_alert20.wav
sound/schall/zombie/zo_attack1.wav
sound/schall/zombie/zo_attack2.wav
sound/schall/zombie/zo_idle1.wav
sound/schall/zombie/zo_idle2.wav
sound/schall/zombie/zo_idle3.wav
sound/schall/zombie/zo_idle4.wav
sound/schall/zombie/zo_pain1.wav
sound/schall/zombie/zo_pain2.wav
